### ISSUE TITLE
renaming of docker-* projects into container-*

### ISSUE THREAD

**Issue by pkrog** [phnmnl/MTBLS233-POP#1]
@mcapuccini 

Hi Marco,

As decided during the [Sixth dedicated WP9 hangout](https://docs.google.com/document/d/1JlHVHFA_u6CqFHOLzwV_9xtzm7FnUJDgiEV9gl3F2Tg/edit) we are currently renaming all docker-\* git repos and jenkins project into container-*.

Could you please push any current modifications you could have, and tell me when you are done. I will make the changes and let you know as you as it's done and operational (Jenkins container build passes).

Regards,
Pierrick

**Comment by mcapuccini** [comment]
Just changed docker-openms to container-openms.

Regards
Marco

**Comment by pkrog** [comment]
Ok, thanks.
I've renamed the Jenkins project, and run a build. It has passed correctly.
I will also rename docker_ex_batch_feature_removal, docker_ex_blankfilter and docker_ex_log2transformation, which are all based on workflow-demo github repos.

**Comment by mcapuccini** [comment]
I guess these can be removed, they were used only for the first tutorial
/Marco
